//WARNING: This file is auto generated by the routes generator.
class RoutesManager {
  static const String myQrScreen = '/myQrScreen';
  static const String qrScannerScreen = '/qrScannerScreen';
  static const String chatScreen = '/chatScreen';
  static const String homeScreen = '/homeScreen';
  static const String lockScreen = '/lockScreen';
}
